# Generated by Django 4.1 on 2022-08-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название прайса', max_length=128, verbose_name='Название')),
                ('email_addres', models.CharField(help_text='Укажите адрес email с которого приходит прайс', max_length=64, verbose_name='Email письма')),
                ('email_title', models.CharField(help_text='Укажите тему письма с которого приходит прайс', max_length=64, verbose_name='Title письма')),
                ('suppliers_id', models.IntegerField(help_text='Укажите ИД поставщика в БД', verbose_name='ИД Поставщика')),
                ('warhouse_id', models.IntegerField(help_text='Укажите ИД склада в Бд, если нужно', verbose_name='ИД Склада')),
                ('clear_line', models.IntegerField(blank=True, default=1, help_text='Количество строк которые нужно пропустить', verbose_name='Пустых строк')),
                ('parser_type', models.CharField(choices=[('file', 'file'), ('zip', 'zip'), ('rar', 'rar')], help_text='Тип вложения в письме', max_length=32, verbose_name='Тип вложения')),
                ('file_type', models.CharField(choices=[('csv', 'csv'), ('xls', 'xls'), ('xlsx', 'xlsx')], help_text='Тип файла прайса', max_length=32, verbose_name='Тип файла')),
                ('file_encoding', models.CharField(blank=True, choices=[('utf-8', 'utf-8'), ('windows-1251', 'windows-1251')], help_text='Кодировка файла (Для файлов CSV)', max_length=32, null=True, verbose_name='Кодировка файла')),
                ('file_delimiter', models.CharField(choices=[('\t', 'Табуляция'), (';', 'Точка с запятой'), (',', 'Запятая')], help_text='Разделитель строк (Для файлов CSV)', max_length=32, verbose_name='Разделитель строк')),
                ('unity', models.TextField(help_text='Json: Соответствие имени файла со складом', verbose_name='Соотмествия файлов')),
                ('colums', models.TextField(help_text='Json: Значение колонок в файле', verbose_name='Соответствия колонок')),
            ],
        ),
    ]
