# Generated by Django 4.1 on 2022-08-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailparser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='clear_line',
            field=models.IntegerField(blank=True, default=0, help_text='Количество строк которые нужно пропустить', verbose_name='Пустых строк'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email_addres',
            field=models.CharField(help_text='Укажите адрес email с которого приходит прайс', max_length=64, null=True, verbose_name='Email письма'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email_title',
            field=models.CharField(help_text='Укажите тему письма с которого приходит прайс', max_length=64, null=True, verbose_name='Title письма'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='file_delimiter',
            field=models.CharField(choices=[('\\t', 'Табуляция'), (';', 'Точка с запятой'), (',', 'Запятая')], help_text='Разделитель строк (Для файлов CSV)', max_length=32, null=True, verbose_name='Разделитель строк'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='unity',
            field=models.TextField(help_text='Json: Соответствие имени файла со складом', null=True, verbose_name='Соотмествия файлов'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='warhouse_id',
            field=models.IntegerField(help_text='Укажите ИД склада в Бд, если нужно', null=True, verbose_name='ИД Склада'),
        ),
    ]
